version: "3.5"

services:
  db:
    image: postgres:alpine
    container_name: api_design_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ApiDesign
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ApiDesign", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  adminer:
    image: adminer
    container_name: api_design_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "echo 'php -r \"phpinfo();\"'"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
